# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x63\x61mera.proto\x12\x06\x63\x61mera\"\x07\n\x05\x42lank\"%\n\x0e\x43\x61meraResponse\x12\x13\n\x0b\x62\x61se64image\x18\x01 \x01(\t2;\n\x06\x43\x61mera\x12\x31\n\x06Stream\x12\r.camera.Blank\x1a\x16.camera.CameraResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_BLANK']._serialized_start = 24
    _globals['_BLANK']._serialized_end = 31
    _globals['_CAMERARESPONSE']._serialized_start = 33
    _globals['_CAMERARESPONSE']._serialized_end = 70
    _globals['_CAMERA']._serialized_start = 72
    _globals['_CAMERA']._serialized_end = 131
# @@protoc_insertion_point(module_scope)
